name: "Boop Gregors nose"
on:
  workflow_dispatch: {}
 
jobs:
  boop:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/boop-gregors-nose@main
        with:
          personal-access-token: ${{ secrets.PAT }}
